name: ci-python-workflow
on: [pull_request]
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python math_test.py
      - run: python math.py